### ISSUE TITLE
DOWNLOAD BACKUP and DOWNLOAD SUPPORT INFO

### ISSUE THREAD

**Issue by MajoV** [oznu/docker-unms#3]
@oznu 
There is unable to DOWNLOAD BACKUP and DOWNLOAD SUPPORT INFO.

![back](https://user-images.githubusercontent.com/26937202/33799533-0af6df5c-dd2e-11e7-83cd-901983571ddb.PNG)

![supp](https://user-images.githubusercontent.com/26937202/33799536-0e405d00-dd2e-11e7-8193-7268f2f49d5e.PNG)

Is this only my issue or is it issue in general?

Majo

**Comment by oznu** [comment]
I can replicate the issue - will check it out.

**Comment by oznu** [comment]
Thanks for raising this issue.

The `Download Backup` button was not working because the program called `redis-dump` was not in the `PATH`.  I have fixed the `PATH` variable to include this.

https://github.com/oznu/docker-unms/blob/49dddf482f0ffa1c17d460fc9a53b501774f81d1/Dockerfile#L30

The `Download Support Info` button wasn't working because the UNMS log directory was empty. I was just dumping all logs to `stdout` which gave the user the choice of using any Docker compatible logging driver they wanted. In this change, I still dump the logs to`stdout` but also write them to a log file so UNMS can bundle them as part of the support info file.

https://github.com/oznu/docker-unms/blob/49dddf482f0ffa1c17d460fc9a53b501774f81d1/root/etc/services.d/unms/run#L14

After making these two minor changes, both those buttons work as expected.

**Comment by MajoV** [comment]
@oznu 
Now it works well. Thank you for your fixes.
