### ISSUE TITLE
UNMS is starting...

### ISSUE THREAD

**Issue by Roberto6969** [oznu/docker-unms#32]
I have tried install UNMS on Raspberry Pi3 three times already but at the end the result is the same all the time. After installation UNMS works fine (can be configured, can manage devices) but after a few days wed interface dies and it shows only "UNMS is starting... This should not take more than a minute". But it takes forever. Raspberry became hot and it is obviously that it is quite active. Also log show that it's activity.
This command does not help: docker-compose restart unms

How can I start up web interface?

Thank you!

**Comment by danteali** [comment]
What does your log (docker log <container_name>) say?

**Comment by cron410** [comment]
I've got the same issue. Here's my logs:

```
1420:M 05 Dec 17:20:12.667 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1420:M 05 Dec 17:20:12.667 # Server started, Redis version 3.2.6
1420:M 05 Dec 17:20:12.667 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1420:M 05 Dec 17:20:12.667 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1420:M 05 Dec 17:20:12.755 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
```

Running on RancherOS x64. I have Autoheal and Watchtower containers running to restart containers that include Healthchecks and pull updates (respectively). Autoheal does not make changes to this container because there is no healthcheck in the dockerfile.

**Comment by danteali** [comment]
I frequently get errors (usually different errors between each version update so nothing I can consistently track down and fix) if I leave UNMS to update to 'latest' with watchtower so I've begun just explicitly specifying an image tag to use and sticking with that until I decide the latest features are worth having - then do a full wipe and 're-install' with fresh volumes.

**Comment by Roberto6969** [comment]
[unms.log](https://github.com/oznu/docker-unms/files/2659730/unms.log)

Here is my log!

BTW: Raspberry became quite hot during this "UNMS is starting"

**Comment by Zaf9670** [comment]
I was experiencing the same issues on my Raspberry Pi. I reformatted the config folder and that seems to have resolved my issues but I'm not sure what was corrupted or conflicting. We had some snow recently that cause quite a few power recycles and it may have developed the issue after attempting to boot several times over.

**Comment by Zaf9670** [comment]
I'm getting the UNMS is starting again and don't really feel like wiping the configuration again. I suppose I'll just disable the docker until it gets update. I also decided to grab one of those PoE Libre Renegade Elite that hopefully will arrive soon and be capable of running UNMS instead of the Pi.

**Comment by Zaf9670** [comment]
Alright just to update again. It looks like whatever is happening is due to the redis aof file.

If you apt-get install redis-server and then go into the /home/pi/config/redis folder you can run the following command. That seemed to bring back my UNMS without resetting the entire configuration.
 
sudo redis-check-aof --fix appendonly.aof

**Comment by r00p** [comment]
Same problem om Synology Nas. Dont know about the redis thing. How to i solve this on a Syn nas?

**Comment by conradKE** [comment]
same problem today it was running fine :-(
